# GitHub Pages configuration for ios.hyper-limit.app
# This config works alongside existing pages at p24l.github.io/Limit

# Include hidden directories (.well-known)
include:
  - .well-known

# Serve the apple-app-site-association file without extension
plugins: []

# Ensure proper MIME type for AASA file
defaults:
  - scope:
      path: ".well-known/apple-app-site-association"
    values:
      layout: null